services:

  web:
    build: .
    container_name: fastapi_movie_app
    command: python app/run.py
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    environment:
      - POSTGRES_HOST=pg
      - MINIO_HOST=minio
    depends_on:
      - pg
      - minio
    volumes:
      - .:/app

  pg:
    image: postgres
    container_name: db_postgres
    env_file:
      - app/.env
    ports:
      - "5432:5432"


  minio:
    image: minio/minio
    container_name: local_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - app/.env
    command: server /data --console-address ":9001"


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_queue
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - app/.env
