services:

  web:
    build: .
    container_name: fastapi_movie_app
    command: python app/run.py
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    depends_on:
      - pg
      - minio
      - redis
      - elasticsearch
      - rabbitmq
      - nats
    volumes:
      - .:/app

  pg:
    image: postgres
    container_name: db_postgres
    env_file:
      - app/.env
    ports:
      - "5432:5432"


  minio:
    image: minio/minio
    container_name: local_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - app/.env
    command: server /data --console-address ":9001"


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_queue
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - app/.env


  nats:
    image: nats:2.10-alpine
    container_name: nats_server
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]


  redis:
    image: redis:8-alpine
    container_name: movie_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"


  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.1
    env_file:
      - app/.env
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch